[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read", path = "./lib/era-contracts/system-contracts/artifacts-zk/contracts-preprocessed" },
    { access = "read", path = "./out" },
    { access = "read", path = "./zkout" },
]

remappings = [
    "contracts/=lib/era-contracts/l1-contracts/contracts",
    "@openzeppelin/contracts-v4/=lib/era-contracts/l1-contracts/lib/openzeppelin-contracts-v4/contracts/",
    "@openzeppelin/contracts-upgradeable-v4/=lib/era-contracts/l1-contracts/lib/openzeppelin-contracts-upgradeable-v4/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options